stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6-jdk-11
  script:
    - 'mvn package'
  tags:
    - docker
  artifacts:
    paths:
      - target/valueplus-0.0.1-SNAPSHOT.jar

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_KEY
    - aws configure set region af-south-1
    - pip install awsebcli --upgrade --user
    - ~/.local/bin/eb deploy ValueplusApplication-env
  dependencies:
    - build
  only:
    - master
