branch-defaults:
  master:
    environment: Valueplusagency-env
global:
  application_name: ValuePlusAgency
  default_ec2_keyname:
  default_platform:
  default_region: af-south-1
  sc: git
  workspace_type: Application
deploy:
  artifact: target/valueplus-0.0.1-SNAPSHOT.jar