package com.valueplus.domain.enums;

public enum ActionType {
    USER_LOGIN,
    USER_PROFILE_UPDATE,
    USER_PIN_UPDATE,
    USER_DISABLE,
    USER_ENABLE,
    USER_CREATE_AGENT,
    USER_CREATE_SUPER_AGENT,
    USER_CREATE_ADMIN,
    USER_AUTHORITY_UPDATE,
    USER_PASSWORD_UPDATE,
    USER_PASSWORD_RESET,
    USER_PROFILE_PICTURE_UPDATE,
    ACCOUNT_CREATE,
    PRODUCT_ORDER_CREATE,
    PRODUCT_ORDER_STATUS_UPDATE,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    SETTING_CHANGE,
    TRANSACTION_INITIATE,
    TRANSACTION_STATUS_CHANGE
}
